### ISSUE TITLE
License footers under "Fortran intrinsics" not rendering correctly

### ISSUE THREAD

**Issue by p-costa** [fortran-lang/webpage#130]
The license footers in the Fortran intrinsics manpages are not rendering correctly.

See an example below from https://fortran-lang.github.io/webpage/en/learn/intrinsics/array:

<img width="497" alt="Screenshot 2022-08-29 at 10 56 39" src="https://user-images.githubusercontent.com/29615530/187186199-d62747f6-ac84-4ca9-84cb-88812ccaafe9.png">

**Comment by henilp105** [comment]
@p-costa @awvwgk this is not a bug but a typo made in the jekyll site. as there are 7 '#' instead of 6 max headings predefined and renders them as `####### fortran-lang intrinsic descriptions (license: MIT) @urbanjost`  . We can surely change all the 212 md files of all the intrinsics file.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
