### ISSUE TITLE
differences between old and new web page

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/webpage#151]
In the previous site the indexing into the intrinsic descriptions was designed for several access methods. There was an
alphabetical index, a short index of major categories that pointed to category indices with short descriptions, and a [NEXT] button on each description ...

https://fortran-lang.github.io/fortran-lang.org/learn/intrinsics

I am wondering if th e new page has any easy ways to recover the look and feel of that interface.

In addition, all the section styles appear to be the same style and size, so things like the license line at the bottom of each page appear quite large (a "###### title" line in the markdown file).  

The "See Also" links are also broken, although I think I can fix that; the previous page used a special index name for the link this interface does not have (?) so regular URLs might work instead.

**Comment by henilp105** [comment]
> There was an alphabetical index, a short index of major categories that pointed to category indices with short descriptions.

Sir, Maybe it seems that you may have missed the non-alphabetical order of major categories in the left side and a categories on current page on the right side. The descriptions can be found on the starting of the every major category.

> In addition, all the section styles appear to be the same style and size, so things like the license line at the bottom of each page appear quite large (a "###### title" line in the markdown file).

@urbanjost Sir, It seems that this may have been due to change of markdown to myst. may be we could change the way of displaying by not using heading just text or so.

> and a [NEXT] button on each description ...

We had discussed about this but the navigations would be enabled globally which would result into the site wide [NEXT] buttons at the bottom of the pages, thus we had decided to exclude it , but maybe we could ENABLE them GLOBALLY.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
We changed the layout to reduce the number of pages, which have to be created and cross-linked, to speed up the build. While the motivation was technical, I think the resulting pages are somewhat nicer since you can easily explore the intrinsic functionality presented in a category by scrolling through.

The copyright statement seems to be a too deep heading to be rendered with sphinx, if we can just make it italic it should work better.

**Comment by urbanjost** [comment]
I tried a document with # A, ## A, ### A, #### A, ##### A, ###### A before posting and they all rendered identically, which was suprising. Originally those lines were intentionally smaller; just as plain text does look better. 

The original layout allowed stepping through alphabetically or by category; in particular that made it easy to review the rendered documents,  perhaps if the NEXT functionality was activated that would suffice. The math is finally rendering, which I still need to review now that it works.  The format is fine and the new site has other advantages but I liked having the index pages having short descriptions, etc. and found it easier to navigate. Overall it is OK and the new site works nicely; but wondering what options there are to explore with the new format. Still reading the Sphinx documentation.

**Comment by urbanjost** [comment]
The copyright notices look better as simple text, so removed the '######'.  Some of the other changes would be nice in my opinion but sound like they become too complicated using the aggregated pages. So it becomes more of a discussion than an issue so closing.
