### ISSUE TITLE
markup code being marked to translation

### ISSUE THREAD

**Issue by 14NGiestas** [fortran-lang/webpage#41]
I found this ["card-img-top"](https://hosted.weblate.org/translate/fortran-lang/webpage/en/?checksum=176795615cfd118b&q=+has%3Acomment+&sort_by=-priority%2Cposition#comments) which looks like it shouldn't be up to translation.

PS: There were a lot of single-worded terms (like the names and arguments of Fortran intrinsic) that shouldn't be translated as well. I had to enter Zen and start skipping/copying the src text for a good amount of time xD so it may be a pain for first-time contributors.

Also, I think the GNU license file should be left out as per FSF's recommendation.

**Comment by henilp105** [comment]
@14NGiestas  
1) I had also noticed this bug but even on adding/not adding translation to strings like above, the pages don't get affected ( I have tested this) and this is a bug due to myst-parser being used as RST is primary language used by Sphinx. but , as it doesn't affect the pages and its subsequent output thus , In my opinion we should maybe ignore them until being fixed by Myst themselves.
2) Regarding the GNU license file we will resolve it in the upcoming PR.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk
